# Generated by Django 5.2.7 on 2025-10-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Тўлиқ исм')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='mentors/', verbose_name='Аватар')),
                ('position', models.CharField(max_length=200, verbose_name='Лавозим')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('years_experience', models.IntegerField(default=0, verbose_name='Тажриба (йил)')),
                ('students_count', models.IntegerField(default=0, verbose_name='Студентлар сони')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Мутахассислик')),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активми?')),
                ('order', models.IntegerField(default=0, verbose_name='Тартиб')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ментор',
                'verbose_name_plural': 'Менторлар',
                'ordering': ['order', '-rating'],
            },
        ),
    ]
