# Generated by Django 5.2.7 on 2025-10-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Номи')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Тавсиф')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Расм')),
                ('level', models.CharField(choices=[('beginner', 'Бошланувчи'), ('intermediate', 'Ўрта'), ('advanced', 'Илғор')], default='beginner', max_length=20, verbose_name='Даража')),
                ('duration_hours', models.IntegerField(default=0, verbose_name='Давомийлик (соат)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бепулми?')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нарх')),
                ('students_count', models.IntegerField(default=0, verbose_name='Талабалар сони')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Чоп этилганми?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курслар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Номи')),
                ('description', models.TextField(blank=True, verbose_name='Тавсиф')),
                ('order', models.IntegerField(default=0, verbose_name='Тартиб')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модул',
                'verbose_name_plural': 'Модуллар',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Номи')),
                ('lesson_type', models.CharField(choices=[('video', 'Видео'), ('text', 'Матн'), ('quiz', 'Квиз'), ('code', 'Код машқи')], default='video', max_length=20, verbose_name='Тур')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео URL')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Давомийлик (дақиқа)')),
                ('order', models.IntegerField(default=0, verbose_name='Тартиб')),
                ('xp_reward', models.IntegerField(default=50, verbose_name='XP бонус')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бепулми?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Модул')),
            ],
            options={
                'verbose_name': 'Дарс',
                'verbose_name_plural': 'Дарслар',
                'ordering': ['order'],
            },
        ),
    ]
