# Generated by Django 5.2.7 on 2025-10-17 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номи')),
                ('description', models.TextField(verbose_name='Тавсиф')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Иконка')),
                ('requirement_type', models.CharField(max_length=50, verbose_name='Шарт тури')),
                ('requirement_value', models.IntegerField(default=0, verbose_name='Керакли миқдор')),
                ('xp_reward', models.IntegerField(default=100, verbose_name='XP бонус')),
            ],
            options={
                'verbose_name': 'Бадж',
                'verbose_name_plural': 'Баджлар',
            },
        ),
        migrations.CreateModel(
            name='XPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Миқдор')),
                ('reason', models.CharField(max_length=200, verbose_name='Сабаб')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP тарих',
                'verbose_name_plural': 'XP тарихлари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фойдаланувчи баджи',
                'verbose_name_plural': 'Фойдаланувчи баджлари',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
